server:
  port: 80
spring:
  application:
    name: cloud-order-service
  # ========================日期格式化=====================
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
# ========================swagger=====================
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html