server:
  port: 8001

# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: cloud-payment-service
  config:
    import: 'optional:consul:'  #关键点 导入外部配置源，读取Consul中的配置
  profiles:
    active: dev #多环境配置 如dev/test/prod，默认为default
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      config:
        enabled: true
        profile-separator: '-'    #文件分隔符，默认使用','  根据我们定义文件名的习惯(如application-dev.yml)修改为'-'
        format: YAML
        watch:
          enabled: false
  # ========================日期格式化=====================
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dongguo.cloud.entity
  configuration:
    map-underscore-to-camel-case: true


# ========================swagger=====================
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# ========================zipkin===================
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。